### ISSUE TITLE
Missing blocking and messaging on Company Portal app deletion

### ISSUE THREAD

**Issue by robaburgess** [msintuneappsdk/ms-intune-app-sdk-android#115]
**Describe the bug:**
With one of our customers, and on Android specifically – the user deletes the Company Portal App after login and is not presented with the expected messaging (see attached video). The customer receives the correct behaviour from the Whiteboard app, but our app does not respond to the deletion of Company Portal.

**To Reproduce**
1. Log into app
2. Exit app
3. Remove Company Portal
4. Log into app

**Expected behavior:**
Expected messaging inside modal, blocking user from continuing 
"To use your work or school account with
this app, you must install the Microsoft
Intune Company Portal app. Tap
"Go to
store" to continue."

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 

https://user-images.githubusercontent.com/74053268/173844736-ccde8096-7696-4296-a3d2-2fbf185a7c15.mov

- If your app is experiencing an issue during build, do you have error logs?
- N/A
- If your app is experiencing an issue post build, do you have app logs for the crash itself?
N/A

**Smartphone (please complete the following information):**
Android

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
Version 8.1.1
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
Flutter, Java
- For errors during build, does the app build without Intune SDK integration?
N/A
- For errors post build, does the app launch without being Intune SDK integrated?
N/A
- Who is the customer?
Ricoh Europe and customers
- Do you see a trend with it only being reproduced on a specific device?
No

**Additional context:**

**Comment by rotamir** [comment]
Hi @robaburgess how many devices is this problem being observed on? Also, does it happen consistently on every sign-out from your app?

**Comment by bannus** [comment]
@robaburgess That message does not represent the expected behavior -- after the Company Portal is uninstalled, it is only shown when a managed app either does not have a registered wipe handler or the wipe handler does not return a successful result. The dialog is shown because the app may have not shown any messaging, and the Intune SDK is about to execute a more heavy-handed wipe using system APIs.

If the customer would like to achieve the same behavior, they can consider not registering any wipe handlers and relying on the default wipe behavior, as described here: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#selective-wipe. Alternatively, they can show their own dialog upon receiving the wipe notification.
