### ISSUE TITLE
Androidx support

### ISSUE THREAD

**Issue by dbsheta** [msintuneappsdk/ms-intune-app-sdk-android#12]
Please add androidx support i.e Androidx class and method mappings. We are developing a business critical application using need to use Intune SDK for MAM. We are having issues when using current sdk as it only supports appcompat v4 and v7.

**Comment by joakley-msft** [comment]
Please see https://docs.microsoft.com/en-us/intune/app-sdk-android#androidx-libraries

**Comment by meghandaly** [comment]
Please see the above link for the SDK documentation regarding the AndroidX libraries.

**Comment by nilsi** [comment]
@meghandaly @joakley-msft I don't understand how this is supposed to work.

I migrated our project to AndroidX because of other reasons and now most classes are red in Android Studio. 

Issues like:

```
ViewModelProviders.of(this, factory).get(MyViewModel.class) 
```
errors because `this` is not an `androidx.appcompat.app.AppCompatActivity`

My activity extends `MAMAppCompatActivity` that when I inspect uses:

```
import android.support.v7.app.AppCompatDelegate;
import android.support.v7.app.MSMAMAppCompatDelegateWrapper;
```
I have added to the build.gradle:
```
intunemam {
    includeExternalLibraries = ["androidx.*"]
}
```

is that supposed to replace all support.v7 references from intunes SDK? Even if it does I feel like Android Studio will backfire here?

I really don't get how this is supposed to work. Are there any examples where you use AndroidX? tasker does not seem to do it. 

My project was fine with intunes before I migrated.

**Comment by nilsi** [comment]
Actually when I look at the taskr app now:

https://github.com/msintuneappsdk/Taskr-Sample-Intune-Android-App/blob/master/app/src/main/java/com/microsoft/intune/samples/taskr/MainActivity.java

The MainActivity inherits directly from AppCompatActivity.

How does that work? I thought I had to wrap every fragment and activity in MAM equivalents to make intune work? 

If I can instead use AppCompatActivity for all my activities and the plugin later does some magic when building I could make it work probably.

**Comment by joakley-msft** [comment]
Hi @nilsi,

That's correct. The plugin will perform the replacements at build time. See [here](https://docs.microsoft.com/en-us/intune/developer/app-sdk-android#build-tooling) for more information.

**Comment by nilsi** [comment]
Thank you for the confirmation. Just one quick question.

So if I use AndroidX for everything in my app I don't need to include any of the following files?

Microsoft.Intune.MAM.SDK.Support.v4
Microsoft.Intune.MAM.SDK.Support.v7
Microsoft.Intune.MAM.SDK.Support.v17
Microsoft.Intune.MAM.SDK.Support.Text.jar

And the only thing that I need to add is

intunemam {
    includeExternalLibraries = ["androidx.*"]
}

To make the plugin intercept all androidx dependencies? How would I know that my app is still MAM compatible after this refactor?

If any of my third party libraries use v4 or v7 I still need to implement these jars?

**Comment by joakley-msft** [comment]
Yes, that's correct. Some steps for testing that policy is applying correctly are documented [here](https://docs.microsoft.com/en-us/intune/developer/app-sdk-android-testing-guide).

If the third-party libraries are being Jetified to convert them to AndroidX, the legacy support jars will still be unnecessary.
