### ISSUE TITLE
Update for compile SDK 33

### ISSUE THREAD

**Issue by richakhanna** [msintuneappsdk/ms-intune-app-sdk-android#121]
At slack we are working on to update android compileSdk to 33 version, but we are hitting few glitches because of current intune library not supported with SDK 33.

It has to do with all methods that are now using `PackageManager.ResolveInfoFlag` as a second parameter. None of these methods like `getPackageInfo()` , `resolveActivity()` etc are updated in `MamPackageManagement.class` to accept the new parameter and that's causing the failure while building.

Stacktrace:
```
Mamification failed: [source error] resolveActivity(android.content.pm.PackageManager,android.content.Intent,android.content.pm.PackageManager$ResolveInfoFlags) 
not found in com.microsoft.intune.mam.client.content.pm.MAMPackageManagement
--
  | javassist.CannotCompileException: [source error] resolveActivity(android.content.pm.PackageManager,android.content.Intent,android.content.pm.PackageManager$ResolveInfoFlags) 
not found in com.microsoft.intune.mam.client.content.pm.MAMPackageManagement
  | at javassist.expr.MethodCall.replace(MethodCall.java:257)
  | at com.microsoft.intune.mam.MethodCallRewriteRule.rewriteWithCallReplace(MethodCallRewriteRule.java:246)
  | at com.microsoft.intune.mam.MethodCallRewriteRule.javassistRewrite(MethodCallRewriteRule.java:233)
  | at com.microsoft.intune.mam.MamifyExprEditor.edit(MamifyExprEditor.java:43)
  | at javassist.expr.ExprEditor.loopBody(ExprEditor.java:197)
  | at javassist.expr.ExprEditor.doit(ExprEditor.java:96)
  | at javassist.CtClassType.instrument(CtClassType.java:1554)
  | at com.microsoft.intune.mam.BuildTimeMamifier.mamifyClass(BuildTimeMamifier.java:454)
  | at com.microsoft.intune.mam.BuildTimeMamifier.mamifyClasses(BuildTimeMamifier.java:195)
  | at com.microsoft.intune.mam.BuildTimeMamifier.mamify(BuildTimeMamifier.java:107)
  | at com.microsoft.intune.mam.MamifyTransformBase.transform(MamifyTransformBase.java:185)
  | at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:281)
  | at com.android.build.gradle.internal.profile.NoOpAnalyticsService.recordBlock(NoOpAnalyticsService.kt:72)
  | at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:239)

```
Please let us know when we can expect the new update with  compile SDK 33.

**Comment by ZacSweers** [comment]
Related - it would be great if this processor could be tuned to gracefully handle unrecognized overloads like this, unless the intent is to fail like this on all matching method names

**Comment by meghandaly** [comment]
The Intune SDK cannot support targeting Android 13 until it is GA-ed. Based on the [expected timeline shared by Google](https://developer.android.com/about/versions/13#android-13-beta-4), this could be as early as this month and at latest September. Historically we have released an SDK for targeting the new Android version on "Day Zero" and it is our intention to do so for Android 13.

For future reference, the current supported MAM SDK APIs can be found in our documentation under [Android versions](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#android-versions). 

@ZacSweers The noisy behavior of the failures is by design. Any graceful handling would mask the fact the the API in question is not supported.

**Comment by ZacSweers** [comment]
Google has already GA'd the android 13 SDK, they intentionally release it in advance of the launch in order for libraries like this to prepare. Please reconsider your decision, thanks!

**Comment by meghandaly** [comment]
@ZacSweers Due to the nature of the MAM SDK we cannot formally support targeting a new Android version until GA. Android 13 is currently on Beta 4.

I understand that the following published by Google, "With Beta 3, Android 13 reaches [Platform Stability](https://developer.android.com/preview/overview#platform_stability), a milestone that means all app-facing behaviors and APIs, including the official API Level 33 SDK and NDK APIs, are now final." may indicate that the SDK is GA-ed, but we have varied experience with that with past releases. 

Our decision, as such, is not in a position to be reconsidered.

**Comment by meghandaly** [comment]
@ZacSweers Let me amend my previous comment. 

We are currently working on SDK support and will make the release available as soon as it is ready. Platform stability does give us a level of confidence that we can release under, although any changes made when Android 13 is GA (we hope none!)  does affect our confidence levels and release timeline.

We appreciate your early adoption and will take this into account for future Android releases.

**Comment by ZacSweers** [comment]
Would you be open to releasing a pre-release version (`8.7.0-beta`, or similar) that we can safely build against? Right now it is impossible for us to use any new Android SDK PackageManager APIs in our main branch due to the above behavior. It prevents _us_ from being ready for Android 13's release as a result, and due to the closed source nature of this project we cannot easily fix this ourselves with an internal fork.

**Comment by ZacSweers** [comment]
@meghandaly Android 13 was released today, can you please provide an ETA?

**Comment by meghandaly** [comment]
@ZacSweers Our next release, SDK 9.0.0 can be expected mid-September. Once it is ready we will make it available here. 

For future Android releases, we are re-evaluating our options for a "pre-release version" as requested.

**Comment by ZacSweers** [comment]
Thanks!
