### ISSUE TITLE
Policy updates are not getting applied

### ISSUE THREAD

**Issue by parveen-bhatia** [msintuneappsdk/ms-intune-app-sdk-android#134]
**Describe the bug:**
After successful authentication (using MSAL) and enrollment (intune SDK). We are getting policy updates. But after changing policies on the intune, policy updates are not being applied. Tried waiting for more than 24hrs and also tried calling `registerAccountForMAM`. But still policy updates are not getting applied.

**Smartphone:**
Android 10.0 (Haven't tried on other Android versions)

**Intune App SDK and MSAL version for Android**
Intune SDK version: 8.3.0
MSAL version: 2.2.3

What platform is your app based in (Java, Xamarin based, Cordova, etc)?
Java, Android native

Logs:
In the logs, able to see following

_I/PolicyChecker: Skipping mustCheckPolicies because compliant is not force and user has not been interrupted._

**Questions:**
How frequently SDK pull for protection policies and is there any API to force it earlier ?
From the logs does it mean the SDK is **skipping** policy check ?
Do we have easy way to test policy updates like can we try changing device system time ?

**Comment by rygo-msft** [comment]
`How frequently SDK pull for protection policies and is there any API to force it earlier ?`
`Do we have easy way to test policy updates like can we try changing device system time ?`
Once successfully enrolled and checked in, the policy will apply for the managed user. We periodically check in for policy updates documented here https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-delivery#delivery-timing-summary.

Calling `registerAccountForMAM` for an already registered user will not do anything since the account is already registered.

To manually force a policy check-in you can follow these docs https://docs.microsoft.com/en-us/mem/intune/user-help/sync-device-android

`From the logs does it mean the SDK is skipping policy check ?`
No, this is an intermediate log message describing one of many steps in our policy enforcement.

I suggest confirming that you are receiving successful enrollment results to your registered notification receiver and that you have implemented and registered your `MAMServiceAuthenticationCallback`. If we cannot retrieve a valid token from your app we will not be able to check-in for policy update. 
https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#account-authentication

**Comment by rygo-msft** [comment]
Closing answered question. Please re-open if you have a follow up question

**Comment by parveen-bhatia** [comment]
@rygo-msft thanks for your response.

1) I saw maximum interval is 24hrs. But found automatic policy updates are very hard to get even after waiting for 24hrs keeping the app active or killing and relaunching it multiple times. So, is it possible to provide API to set the time interval ?
2) Manually applying updates from company portal works fine
3) Yes, we have already implemented `MAMServiceAuthenticationCallback` and SDK is able to acquire token from the MSAL cache.
