### ISSUE TITLE
Since Gradle 8 - Cannot use @TaskAction annotation on method IncrementalTransformTask.transform()

### ISSUE THREAD

**Issue by yvan-botella** [msintuneappsdk/ms-intune-app-sdk-android#157]
**Describe the bug:**

**To Reproduce**
- from gradle 8 `distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.1-bin.zip`
- build app
- build failed on `transformClassesWithMamifyTransformForCiOptiDebug`
- See error

**Expected behavior:**
App should build without error

**Screenshots and logs:**
```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not create task ':app:transformClassesWithMamifyTransformForCiOptiDebug'.
   > Cannot use @TaskAction annotation on method IncrementalTransformTask.transform() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
```

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
`SDK 9.4.0`
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
`Java / Kotlin`
- For errors during build, does the app build without Intune SDK integration?
`YES`
- For errors post build, does the app launch without being Intune SDK integrated?
`N/A`
- Who is the customer?
`N/A`
- Do you see a trend with it only being reproduced on a specific device?
`N/A`

**Comment by bannus** [comment]
I can reproduce this with AGP 7.4.1 and Gradle 8.0.1. Google has stated that AGP 7.x is not guaranteed to work with Gradle 8.x, see below. You should remain on Gradle 7 until AGP 8 has been released.


> This alignment indicates that AGP 7.x is meant to work with Gradle 7.x APIs. While it may also run on Gradle 8.x, this is not guaranteed and will depend on whether 8.x removes APIs that AGP relies on.

(via https://android-developers.googleblog.com/2020/12/announcing-android-gradle-plugin.html)

I also confirmed that this issue is fixed by using the `-preview` version of the Intune App SDK build plugin, [available in version 9.4.0](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/blob/master/CHANGELOG.md#version-940) and above. (Note that the preview version will become the default for apps consuming AGP 8+).
