### ISSUE TITLE
[Question] Adding Intune specific Scope on Msal Authentication

### ISSUE THREAD

**Issue by GowthamAshokkumar** [msintuneappsdk/ms-intune-app-sdk-android#230]
We're integrating the scope https://msmamservice.api.application/DeviceManagementManagedApps.ReadWrite into our MSAL authentication process to seek admin consent for permissions. However, we haven't found any documentation specifically outlining this scope. We did discover documentation mentioning other scopes [here](https://learn.microsoft.com/en-gb/entra/identity-platform/scopes-oidc?WT.mc_id=UI_AAD_Registered_Apps_Troubleshooting_L2_Overview).

Given the lack of specific documentation, can we assume it's safe to statically include this scope in our code without expecting it to change in the future?

**Comment by ChismanRaheem** [comment]
@GowthamAshokkumar This is a beta Api, you may include this scope, but it's recommended for nonproduction applications since APIs under the /beta version in Microsoft Graph are subject to change. You can also review our public documentation that covers this api in more details- https://learn.microsoft.com/en-us/graph/api/intune-shared-devicemanagement-get?view=graph-rest-beta
