### ISSUE TITLE
Not able to hit external API  because automatically hit auth2 url

### ISSUE THREAD

**Issue by navjyot** [msintuneappsdk/ms-intune-app-sdk-android#45]
We have integrated the In-tune SDK but when we try to hit our server API that will automatically redirect on authority URL,even user is validated from company portal while launching the app.

**Comment by navjyot** [comment]
@msintuneappsdk @oydang @joakley-msft @anavathe Did you guys face same issue while integrating the in-tune SDK  in LOB app.

We have integrated the In-tune SDK but when we try to hit our server API that will automatically redirect on authority URL,even user is validated from company portal while launching the app.

**Comment by joakley-msft** [comment]
This issue is over a year old and does not contain enough information for us to take direction action. We have instituted new practices for monitoring issues regularly. Please re-open if this is still occurring. Note that the Intune MAM SDK cannot control the action of your server, so we will need more information about what mechanism you would expect to control your server behavior here (e.g. are you passing an authentication token from your app to the server, does the server look for specific claims in that token before deciding to redirect, etc)
