### ISSUE TITLE
APP-WE Policy didn't apply after registerAccountForMAM called.

### ISSUE THREAD

**Issue by fongja** [msintuneappsdk/ms-intune-app-sdk-android#49]
We are integrating our LOB app with Intune APP-WE. After we successfully acquire token from ADAL. We call registerAccountForMAM to register MAM and acquire APP-WE policy. The policy is then being downloaded and the status of enrollment is success.

However the policy didn't apply immediately. It didn't prompt user to set PIN that required in the policy.

When will the policy apply after being download? Are there any API can force applying policy immediately?

On iOS it stated in the documentation that it require the app to force restart in order to apply policy. But there is no such information in Android documentation?

**Comment by ClaudioConsolmagno** [comment]
I am also trying to figure out the same information. @fongja have you ever found out?

**Comment by joakley-msft** [comment]
This is by design as MAM enrollment is asynchronous. The only mechanism to force policy to be present before the app can be used is APP CA as documented at https://docs.microsoft.com/en-us/mem/intune/protect/app-based-conditional-access-intune. Directions on supporting APP CA in your app can be found at https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#app-protection-ca

**Comment by ClaudioConsolmagno** [comment]
It's been years and I left the organisation that integrated with Intune. From what I recall we had to implement some sort of busy-wait on the enrollment so you could only continue after that completed successfully and the policies downloaded.

I don't remember if at this point we forced the user to restart the app, but yeah I remember something about certain restrictions (like setting an app pin) only taking effect after a restart.
