### ISSUE TITLE
MSAL and Intune SDK

### ISSUE THREAD

**Issue by VicMikhailau** [msintuneappsdk/ms-intune-app-sdk-android#8]
Hello again,

1. It is possible use MSAL authentication instead ADAL (I think not)?
2. In my app used MSAL for other purposes. A received NullPointerException  because in my policy settings in Azure Portal included "Allow app to transfer data to other apps  - None". It happened because MSAL library included authorization through "Google Custom tabs (I think)". Can I exclude MSAL library from this policy or? .

Thanks

**Comment by scarrilho** [comment]
Hi,
Any updates on this? I mean, does the Android Intune SDK support MSAL?

Release 6.3.0 (https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases/tag/6.3.0) mentions "App developers wishing to use Microsoft Authentication Library (MSAL) should be using this version of the Intune SDK for Android at minimum." . Does it mean that unofficially MSAL works?

I checked that iOS SDK supports MSAL since release 11.1.2 (https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/tag/11.1.2)

**Comment by viveknegi51288** [comment]
@VicMikhailau @scarrilho  DId you get any solution ?

**Comment by staticvoid7** [comment]
[Taskr-Sample-Intune-Android-App](https://github.com/msintuneappsdk/Taskr-Sample-Intune-Android-App) has been updated and uses MSAL since version 2.0.

**Comment by meghandaly** [comment]
The SDK currently supports MSAL integration, for integration guidance see [Configure Microsoft Authentication Library (MSAL)](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#configure-microsoft-authentication-library-msal).
