### ISSUE TITLE
Failed to build with dagger hilt

### ISSUE THREAD

**Issue by bryancaray-ubs** [msintuneappsdk/ms-intune-app-sdk-android#89]
Hi ,

I was unable to build my application once i change from Application to MAMApplication

I am Receiving [Error](url)
onCreate() in Hilt_BaseApplication cannot override onCreate() in MAMApplication
overridden method is final because hilt is overriding the onCreate Function.

@HiltAndroidApp
class BaseApplication : MAMApplication() {

**Comment by codylund** [comment]
Hi @bryancaray-ubs, can you confirm that you are applying the Gradle Build Plug-in to your application as described [here](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#gradle-build-plugin)? 

If you are manually changing the super class from `Application` to `MAMApplication` you must also manually change a number of method overrides in your custom class, including `onCreate()` to `onMAMCreate()`. I suspect this could be the source of your error. However, instead of manually integrating the MAM SDK in this way, we strongly suggest using the Gradle Build Plug-in instead. It will perform all of these replacements automatically at build time.

**Comment by joakley-msft** [comment]
No reply to information request in over a month, closing. Please feel free to reactivate with the request.
